name: Deploy
description: 'Request a deployment'
title: 'New deployment request: '
labels: deploy
body:
  - type: markdown
    attributes:
      value: |
        This issue allows to request a deployment
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, why is this needed?
      placeholder: Tell us why is this needed!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: environment        
    validations:
      required: true
    attributes:
      label: 'Environment:'
      description: Which environment should we target
      options:
        - Production
        - Test
        - Sandbox
  - type: dropdown
    id: runner_labels
    attributes:
      label: 'Runner Labels:'
      description: Which labels should this runner have
      multiple: true
      options:
        - self-hosted
        - node
        - java
        - docker
