name: Branch CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Node CI
        uses: octodemo/devoxx-2021-node@main
        with:
          node-version: ${{ matrix.node }}
